apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
data:
  guestbook-name: "MyPopRock Festival 2.0"
  backend-uri: "http://backend-myproject.2886795279-80-host19nc.environments.katacoda.com/guestbook"
